format = "$hostname$directory$git_branch$git_commit$git_state$git_metrics$git_status$python$character"
right_format = "$time"

add_newline = false

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold green)"

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 3

[hostname]
ssh_only = true

[python]
format = '[(\($virtualenv\) )]($style)'

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"
