format = "$hostname$directory$git_branch$git_status$python$character"
right_format = "$time"

add_newline = false

[character]
success_symbol = "[\\$](bold blue)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[<](bold blue)"

[directory]
fish_style_pwd_dir_length = 1
truncation_length = 3
style = 'bold green'

[git_branch]
format = 'on [$branch(:$remote_branch)]($style) '
style = 'bold yellow'

[git_status]
modified = '✘'
up_to_date = '✓'

[hostname]
ssh_only = true

[python]
format = '[(\($virtualenv\) )]($style)'

[time]
disabled = false
style = "bold bright-black"
format = "[$time]($style)"
