import = [
    "~/.config/alacritty/themes/gruvbox_dark.toml"
]

[window]
dimensions = { columns = 110, lines = 30 }
padding = { x = 14, y = 14 }
decorations = "Buttonless"
# opacity = 0.95

[font]
normal = { family = "JetBrains Mono", style = "Light" }
size = 18

[keyboard]
bindings = [{ key = "F", mods = "Control", action = "ToggleMaximized"},]
