#import = [
#    "~/.config/alacritty/themes/gruvbox_dark.toml"
#]

[shell]
program = "/opt/homebrew/bin/tmux"

[window]
dimensions = { columns = 110, lines = 30 }
padding = { x = 10, y = 10 }
decorations = "Buttonless"
opacity = 0.99

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Regular" }
size = 18

[keyboard]
bindings = [{ key = "F", mods = "Control", action = "ToggleMaximized"},]
